# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e869c596f6bc0250dcb61b944a9c07e4879099155dba66c09af5dc2bb7eadc228d69d5c2ad27bbfaea058174f22380c74a42318646f2a27844579eb32a9711f

test:
  secret_key_base: dac92dca061875bafacdc7472bf1de58e992c49c0e2dcdee28de1e97627770952a939d84d652a1d4064e9ffe05e44e2159dec6d19d170f083a6cccc72d73f38d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
